---
version: 2
jobs:
  build:
    docker:
      - image: jekyll/builder
      #- image: softinstigate/jekyll
      #- image: mesosphere/aws-cli
      
    working_directory: ~/code

    
    environment:
      JEKYLL_ENV: dev
      JOB_RESULTS_PATH: run-results
    
    steps:
      # Checkout the repository
      - checkout

      - run: cd ~/code
      #- run: jekyll build


      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle

      # Deploy html to S3
      #- run: aws s3 sync --exclude="*" ~/code/site/ s3://paulc.me/ --delete
      - run: bundle exec jekyll build --config _config.yml --source . --destination _site/ 2>&1 | tee $JOB_RESULTS_PATH/build-results.txt


